### ISSUE TITLE
能不能直接构建为docker镜像以方便使用

### ISSUE THREAD

**Issue by hzykj** [lyswhut/lx-music-sync-server#4]
希望能够直接构建生成为docker镜像，拉取后直接使用

**Comment by esme518** [comment]
我自建了个镜像 支持x86和arm64 欢迎取用
[esme518/docker-lx-music-sync-server](https://hub.docker.com/r/esme518/docker-lx-music-sync-server)

**Comment by cellistV** [comment]
> 我自建了个镜像 支持x86和arm64 欢迎取用 [esme518/docker-lx-music-sync-server](https://hub.docker.com/r/esme518/docker-lx-music-sync-server)

docker配置可以分享下吗，自己配置显示forbidden了

**Comment by esme518** [comment]
> > 我自建了个镜像 支持x86和arm64 欢迎取用 [esme518/docker-lx-music-sync-server](https://hub.docker.com/r/esme518/docker-lx-music-sync-server)
> 
> docker配置可以分享下吗，自己配置显示forbidden了

如果是浏览器直接访问的话 forbidden是正常现象 只能用软件连接 然后后看看log正常就OK
你可以参考下 [esme518/docker-lx-music-sync-server](https://github.com/esme518/docker-lx-music-sync-server)

**Comment by cellistV** [comment]
> > > 我自建了个镜像 支持x86和arm64 欢迎取用 [esme518/docker-lx-music-sync-server](https://hub.docker.com/r/esme518/docker-lx-music-sync-server)
> > 
> > 
> > docker配置可以分享下吗，自己配置显示forbidden了
> 
> 如果是浏览器直接访问的话 forbidden是正常现象 只能用软件连接 然后后看看log正常就OK 你可以参考下 [esme518/docker-lx-music-sync-server](https://github.com/esme518/docker-lx-music-sync-server)


感谢
测试了一下确实如此，我以为forbidden是出了问题。
请问NMP反代后，报错“401 Unauthorized”，是什么原因呢

**Comment by cellistV** [comment]
> > > > > 我自建了个镜像 支持x86和arm64 欢迎取用 [esme518/docker-lx-music-sync-server](https://hub.docker.com/r/esme518/docker-lx-music-sync-server)
> > > > 
> > > > 
> > > > docker配置可以分享下吗，自己配置显示forbidden了
> > > 
> > > 
> > > 如果是浏览器直接访问的话 forbidden是正常现象 只能用软件连接 然后后看看log正常就OK 你可以参考下 [esme518/docker-lx-music-sync-server](https://github.com/esme518/docker-lx-music-sync-server)
> > 
> > 
> > 感谢 测试了一下确实如此，我以为forbidden是出了问题。 请问NMP反代后，报错“401 Unauthorized”，是什么原因呢
> 
> 具体要看你的反代设置了 你可以参考项目说明里的nginx设置 另外我用的是traefik 加了https没有任何问题

找不到原因，浏览器内外网地址访问都是正常的，就是不能同步，报401，等更新了，谢谢

**Comment by zouxingyuks** [comment]
version: '3'
services:
  lx-music:
    container_name: lx-music
    image: esme518/docker-lx-music-sync-server
    ports:
      - "6666:9527"
    environment:
      - BIND_IP=0.0.0.0
      - LX_USER_user1=你的密码
    restart: always

volumes:
  logvolume01: { }

**Comment by rebron1900** [comment]
分享一下我的配置.
```yaml
---
version: '3'
services:
  lx-music:
    container_name: lx-music
    image: esme518/docker-lx-music-sync-server
    ports:
      - "25254:9527"
    environment:
      - BIND_IP=0.0.0.0
      - LX_USER_user1=密码
    restart: always
    volumes:
      - /data/lx-data/:/server/data
```
