### ISSUE TITLE
使用docker部署出错decrypt message error: Error: unexpected end of file

### ISSUE THREAD

**Issue by UntaggedRui** [lyswhut/lx-music-sync-server#59]
docker-compose.yml文件如下
```yaml
version: '3.3'
services:
    lx-music:
        ports:
            - '8006:9527'
        volumes:
                - './data/config.js:/server/config.js'
                - './data/syncdata:/server/data'
        image: 'lyswhut/lx-music-sync-server'
        networks:
                - mynet
networks:
        mynet:
                external: true
```
已经删除了`rm -rf /data/syncdata`。连接后出现
<img width="1010" alt="image" src="https://github.com/lyswhut/lx-music-sync-server/assets/28807947/bc3c3a45-9ce2-4bc1-821c-0250e636b1cc">
